### PR TITLE
add support for Semtech LR1110 on Nucleo L476RG

### PR DESCRIPTION
**Pull request by K4KDR**
**Semtech LR1110** module (https://www.semtech.com/products/wireless-rf/lora-edge/lr1110mb1lcks) on **Nucleo L476RG** microcontroller (https://www.st.com/en/evaluation-tools/nucleo-l476rg.html)

### CODE REVIEW

**Comment by jgromes** [comment]
Hi Scott,

Thank you for the contribution, however, I'm afraid that this shield is out-of-scope here. As per my comment in the original RadioLib discussion (https://github.com/jgromes/RadioLib/discussions/1106#discussioncomment-9582896):

> So in my point-of-view, Heltec boards are applicable (since the user would need to literally start cutting traces to change the pinout), and so is the Pico hat because it is explicitly intended just for RPi Pico. On the other hand, generic Arduino shield with some radio is out of scope since the pins to which it is connected change depending on what Arduino board you connect it to.

I would say this remains the same - the pins will change if I plug the shield into some board that has the Arduino shield headers.

**Comment by K4KDR** [comment]
Ahh, very good - thanks!

I thought I was doing the right thing based on:

`Suported boards are split between maintained (which we have tested personally) and contributed (which were added by other people).`

... and mistakenly thought you were looking for proven good or officially documented configurations.  The SemTech LR1110 board does plug into the Arduino footprint socket on the Nucleo L476RG, so that also led me to think it was an example of what was being documented in this repository.

No problem!  Feel free to close this any time.

**Comment by jgromes** [comment]
I wouldn't completely rule out shields being - we *could* use the Arduino `D0` etc. pin numbers, but that of course hinges on the platform/Arduino core defining them. STM support in that regard is on a very high level, but it's more the exception than the norm, and mainly it's about drawing the line somewhere.

However, I do think that the Raspberry Pi Pico hat you have added in https://github.com/jgromes/RadioLib/pull/1086 is valid here, because it's targeting the Pico exclusively. I suggest we give this little project a bit more time to take shape and then I will be happy to merge it here. Thanks!

**Comment by K4KDR** [comment]
Great!   I'll work on documenting the Pi-Pico settings to possibly add here if you wish.

Appreciate all the help!

**Pull request closed without merging**
